const appName = 'Awake';

export const en = {
    // Pages
    home: 'Home',
    profile: 'PROFILE',

    // Links
    homeLink: '/',
    locationLink: 'location',
    profileLink: 'profile',

    // Generic
    appName: appName,
    termsOfUse: 'Terms of use',
    smsCodeIncorrect: 'SMS code incorrect',
    error: 'Error',
    alert: 'Alert',
    editProfile: 'Edit Profile',
    addNewSite: 'Add new site',
    addNewPage: 'Add new page',
    uploadPhoto: 'Upload Photo',
    changeAvatar: 'Change Avatar',
    uploadNewImg: 'Upload new image',
    minimumImgSize: 'At least 256x256px PNG or JPG file',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    deleteAccount: 'Delete account',
    fullName: 'Full Name',
    username: 'Username',
    backupEmail: 'Backup Email',
    sms: 'SMS',
    email: 'Email',
    shortBiography: 'Short Biography',
    bio: 'Biography',
    mainProfile: 'Main Profile',
    dataCollection: 'Data Collection',
    dashboard: 'Dashboard',
    mySites: 'My Sites',
    browse: 'Browse',
    signin: 'Sign In',
    logout: 'Log out',
    verification: 'Verification',
    confirmCode: 'Confirm code',
    readyToResend: 'Resend',
    resendingIn: 'Resend code in {number}s',
    allRightsReserved: 'All rights Reserved',
    continue: 'Continue',
    sendVerification: 'Send verification',
    sections: 'Sections',
    settings: 'Settings',
    preview: 'Preview',
    save: 'Save',
    saved: 'Saved Correctly',
    aboutUs: 'About Us',
    backToPages: 'Back to Pages',
    back: 'Back',
    draftContent: 'Draft Content',
    addSection: 'Add section',
    siteUrl: 'Site URL',
    mainColorOfSite: 'Main color of site',
    metaTags: 'Meta tags',
    pressEnterToSubmitMetaTag: 'Press enter to submit metatag',
    colorVersion: 'Color version',
    uploadVideo: 'Upload Video',
    youtubeEmbed: 'YouTube embed',
    editText: 'Edit Text',
    editImage: 'Edit Image',
    editVideo: 'Edit Video',
    delete: 'Delete',
    publish: 'Publish',
    publishing: 'Publishing',
    unPublish: 'Unpublish',
    unPublishing: 'Unpublishing',
    visits: 'Visits',
    impressions: 'Impressions',
    earnings: 'Earnings',
    editPage: 'Edit Page',
    adViews: 'Ad Views',
    siteName: 'Site name',
    stats: 'Stats',
    pageName: 'Page name',
    pageUrl: 'Page URL',
    dateUpdated: 'Date Updated',
    description: 'Description',
    uploadIcon: 'Upload Icon',
    newPage: 'New page',
    sites: 'Sites',
    myPages: 'My Pages',
    pages: 'Pages',
    sitesInTotal: 'sites in total',
    pagesInTotal: 'pages in total',
    totalVisits: 'Total Visits',
    totalEarnings: 'Total Earnings',
    viewPages: 'View Pages',
    subscribeToSite: 'Subscribe to Site',
    unsubscribeToSite: 'Unsubscribe to Site',
    viewPage: 'VIEW PAGE',
    trendingPages: 'Trending Pages',
    popularPages: 'Popular Pages',
    newPages: 'New Pages',
    likes: 'Likes',
    dislikes: 'Dislikes',
    unlikes: 'Unlikes',
    views: 'Views',
    share: 'Share',
    dataPoints: 'Data Points',
    continueWithApp: `Continue with ${appName}`,
    products: 'Products',
    posts: 'Posts',
    showMore: 'Show more',
    loadMore: 'Load More',
    loading: 'Loading',
    data: 'Data',
    hey: 'Hey',
    sortBy: 'Sort by',
    all: 'All',
    discover: 'Discover',
    myData: 'My Data',
    analysis: 'Analysis',
    trending: 'Trending',
    new: 'New',
    popular: 'Popular',
    ITCommunity: 'IT Community',
    category: 'Category',
    searchDataYouDoLike: 'Search data you do like...',
    seoFriendly: 'This is related to SEO',
    reasonDescription: 'Reason Description',
    report: 'Report',
    yourData: 'Your Data',
    awakenedPlatform: 'What is Awake?',
    subscriptions: 'Subscriptions',
    iUnderstand: 'I understand',
    openData: 'Open Data',
    whynocookies: 'Why no cookies?',
    there: 'There',
    pageURLMatchInfo: 'Page URLs must be lowercase with hypthens (-) only',
    siteURLMatchInfo: 'Site URLs must be lowercase with hypthens (-) only',
    addNewData: 'Add New data',
    removeGroup: 'Remove Group',
    removeData: 'Remove Data',
    moveData: 'Move data',
    close: 'Close',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    users: 'Users',
    newUsers: 'New Users',
    dataCollected: 'Data Collected',
    newSites: 'New Sites',
    totalAppUsers: `Total ${appName} users`,
    newUsersThisMonth: 'New users this month',
    newUsersThisWeek: 'New users this week',
    newUsersThisYear: 'New users this year',
    dataCollectedByAllUsers: 'Data collected by all users',
    sitesCreatedThisMonth: 'Sites created this month',
    sitesCreatedThisWeek: 'Sites created this week',
    sitesCreatedThisYear: 'Sites created this year',
    newCustomers: 'New Customers',
    viewMoreCustomers: 'View More Customers',
    customerID: 'Customer ID',
    overview: 'Overview',
    show: 'Show',
    thisYear: 'This Year',
    thisMonth: 'This Month',
    thisWeek: 'This Week',
    appSites: `${appName} Sites`,
    appUsers: `${appName} Users`,
    appPages: `${appName} Pages`,
    options: 'Options',
    reported: 'Reported',
    date: 'Date',
    author: 'Author',
    admin: 'Admin',
    dataFilters: 'Data Filters',
    viewSite: 'View Site',
    block: 'Block',
    viewDetails: 'View Details',
    explicitFrames: 'Explicit Frames',
    failedTime: 'Failed Time',
    likelihood: 'Likelihood',
    phoneNumber: 'Phone Number',
    dateCreated: 'Date Created',
    signedUp: 'Signed Up',
    Status: 'Status',
    active: 'Active',
    blocked: 'Blocked',
    sureToBlockThisUser: 'Are you sure you want to block this user?',
    ok: 'Ok',
    termsAndConditions: 'Terms and Conditions',
    privacyPolicy: 'Privacy Policy',
    acceptVideo: 'Are you sure you want to accept the video? Accepting the video will approve the potential explicit video and show across the platform.',
    rejectVideo: 'Are you sure you want to reject the video? Rejecting the video will delete the potential explicit video from the platform.',
    videoUrl: 'Video URL',
    videos: 'Videos',
    fileName: 'Video File Name',
    processStartedAt: 'Process Started At',
    webOptimization: 'Web Optimization',
    explicitContentFilter: 'Explicit Content Filter',
    optional: 'Optional',
    videoFileMissing: 'Video file missing. Please add a video file to upload.',
    videoTitle: 'Video Title',
    videoDescription: 'Video Description',
    processing: 'Processing',
    importVideo: 'Import Video File',
    maximumVideoUpload: 'Maximum upload: 2 GB size and 1 hour 30 minutes length',
    videoProcessings: 'Video Processings',
    videoUploadError: 'Error occurred while uploading video. Please try again!',
    emailUpdated: 'A confirmation email has been sent to your email, please check your mail to complete editing your profile.',
    accept: 'Accept',
    reject: 'Reject',
    videoMaxSizeError: 'Error occurred while uploading video. Make sure your video is 2GB or less and try uploading again.',
    videoProcessingContactAdmin: 'The video you submitted is getting processed. If this doesn\'t happen automatically within an hour. Please contact admin.',
    dropFilesHere: 'Drop your files here',
    or: 'or',
    comingSoon: 'Coming Soon',
    areYouSure: 'Are you sure?',
    notShowBanned: 'Don\'t Show Banned',
    reports: 'Reports',
    sureDeleteYou: 'Are you sure, this will delete all your data?',
    menu: 'Menu',
    desktop: "Desktop",
    tablet: "Tablet",
    mobile: "Mobile",
    characters: 'characters',
    charactersLeft: "characters remaning",
    tooMany: 'too many',
    maximum: 'Maximum',
    minimum: 'minimum',
    myAds: 'My Ads',
    collectedDataTagsWhenVisitingPage: 'Data tags collected when visiting this page',
    leaveCommentOnThisPost: 'Leave a comment on this post!',
    reply: 'Reply',
    replies: 'Replies',
    commentDeleted: 'Comment Deleted',
    hiddenReplies: 'Hidden Replies',
    post: 'Post',
    comments: 'Comments',
    loadMoreComments: 'Load more comments',
    loadMoreReplies: 'Load more replies',
    dataTags: 'Data Tags',
    awakenedSite: 'Awakened Site',
    no: 'No',
    awakeDescription: `Awake is a platform that allows you to regain control and learn the value of your data across the internet.
        Our partners report data to the platform when you decide to 'Continue with Awake', giving you the data transparency you deserve.`,

    // errors
    invalidFields: 'Some Fields are invalid, please check',
    unauthorised: 'You are not authorized to make this request',
    invalidPhoneNumber: 'You entered the invalid phone number, Please check',
    concurrentSendSMS: 'You recently logged in, please try again later. You must wait 5 minutes if you attempted to login via SMS and failed.',
    sendSMSFailed: 'Something went wrong to send SMS code. Please try again later',
    incorrectSMSCode: 'Your entered SMS code was not correct. Please input the correct code or try again',
    smsConfirmFailed: 'Something went wrong to confirm the SMS. Please try again later',
    usernameExsitsPleaseTryAnother: "Username exists, please try another.",
    sendVerificationEmailFail: 'We failed to send a verification email, please try again later.',
    invalidPhoto: 'Hehe, Your photo is violated to our policy. Please use another photo',
    noUserExists: 'Oops. There is no user matching the information you entered',
    emailNotConfirmed: 'Unfortunately, your email was not confirmed. Please try to use another email',
    headerAlwaysFirst: 'The header should always be at the start',
    tooManySections: 'You are adding too many sections',
    undefinedImagePosition: 'Please make sure where you want to add image.',
    alreadyReported: 'You already reported this page',
    alreadyHeaderExists: 'You already added header.',
    alreadyBlacklisted: 'That category was already blacklisted.',
    noSiteOwner: 'You are not a site owner.',
    pageUrlNotUnique: 'Page URL should be unique.',
    siteUrlNotUnique: 'Site URL should be unique.',
    commentLimitReached: 'You can only comment once every so often',

    // colors
    purple: 'Purple',
    orange: 'Orange',
    green: 'Green',
    red: 'Red',
    light: 'Light',
    dark: 'Dark',

    // section types
    header: 'Header',
    'text-block': 'Text-Block',
    'text-image-right': 'Text-Image-Right',
    'text-image-left': 'Text-Image-Left',
    'image-row': 'Image-Row',
    'video-block': 'Video-Block',
    'video-row-embed-only': 'Video-Row-Embed-Only',
    'triple-image-col': 'Triple-Image-Col',

    // country language code
    nr: 'Norsk',
    en: 'English'
};
