export const Categories = {
    "AIDS & HIV": "AIDS & HIV",
    "Accounting & Auditing": "Accounting & Auditing",
    "Acting & Theater": "Acting & Theater",
    "Adult": "Adult",
    "Advertising & Marketing": "Advertising & Marketing",
    "Aerospace & Defense": "Aerospace & Defense",
    "Affiliate Programs": "Affiliate Programs",
    "Aging & Geriatrics": "Aging & Geriatrics",
    "Agricultural Equipment": "Agricultural Equipment",
    "Agriculture & Forestry": "Agriculture & Forestry",
    "Air Travel": "Air Travel",
    "Airport Parking & Transportation": "Airport Parking & Transportation",
    "Alcoholic Beverages": "Alcoholic Beverages",
    "Allergies": "Allergies",
    "American Football": "American Football",
    "Animal Products & Services": "Animal Products & Services",
    "Animal Sports": "Animal Sports",
    "Anime & Manga": "Anime & Manga",
    "Antiques & Collectibles": "Antiques & Collectibles",
    "Anxiety & Stress": "Anxiety & Stress",
    "Apparel": "Apparel",
    "Arcade & Coin-Op Games": "Arcade & Coin-Op Games",
    "Architecture": "Architecture",
    "Art Museums & Galleries": "Art Museums & Galleries",
    "Arthritis": "Arthritis",
    "Arts & Entertainment": "Arts & Entertainment",
    "Assisted Living & Long Term Care": "Assisted Living & Long Term Care",
    "Astronomy": "Astronomy",
    "Athletic Apparel": "Athletic Apparel",
    "Atmospheric Science": "Atmospheric Science",
    "Auctions": "Auctions",
    "Audio Equipment": "Audio Equipment",
    "Australian Football": "Australian Football",
    "Automotive Industry": "Automotive Industry",
    "Autos & Vehicles": "Autos & Vehicles",
    "BBQ & Grilling": "BBQ & Grilling",
    "BMX Bikes": "BMX Bikes",
    "Baked Goods": "Baked Goods",
    "Bank-Owned & Foreclosed Properties": "Bank-Owned & Foreclosed Properties",
    "Banking": "Banking",
    "Bankruptcy": "Bankruptcy",
    "Bars, Clubs & Nightlife": "Bars, Clubs & Nightlife",
    "Baseball": "Baseball",
    "Basketball": "Basketball",
    "Bathroom": "Bathroom",
    "Beaches & Islands": "Beaches & Islands",
    "Beauty & Fitness": "Beauty & Fitness",
    "Beauty Pageants": "Beauty Pageants",
    "Bed & Bath": "Bed & Bath",
    "Beverages": "Beverages",
    "Bicycles & Accessories": "Bicycles & Accessories",
    "Bike Parts & Repair": "Bike Parts & Repair",
    "Billiards": "Billiards",
    "Billing & Invoicing": "Billing & Invoicing",
    "Biographies & Quotations": "Biographies & Quotations",
    "Biological Sciences": "Biological Sciences",
    "Birds": "Birds",
    "Blogging Resources & Services": "Blogging Resources & Services",
    "Board Games": "Board Games",
    "Boating": "Boating",
    "Boats & Watercraft": "Boats & Watercraft",
    "Body Art": "Body Art",
    "Books & Literature": "Books & Literature",
    "Boxing": "Boxing",
    "Breakfast Foods": "Breakfast Foods",
    "Building Materials & Supplies": "Building Materials & Supplies",
    "Building Toys": "Building Toys",
    "Bus & Rail": "Bus & Rail",
    "Business & Industrial": "Business & Industrial",
    "Business & Personal Listings": "Business & Personal Listings",
    "Business & Productivity Software": "Business & Productivity Software",
    "Business Education": "Business Education",
    "Business Finance": "Business Finance",
    "Business News": "Business News",
    "Business Operations": "Business Operations",
    "Business Plans & Presentations": "Business Plans & Presentations",
    "Business Services": "Business Services",
    "CAD & CAM": "CAD & CAM",
    "CD & Audio Shopping": "CD & Audio Shopping",
    "Cable & Satellite Providers": "Cable & Satellite Providers",
    "Calculators & Reference Tools": "Calculators & Reference Tools",
    "Camera & Photo Equipment": "Camera & Photo Equipment",
    "Campers & RVs": "Campers & RVs",
    "Cancer": "Cancer",
    "Candy & Sweets": "Candy & Sweets",
    "Car Electronics": "Car Electronics",
    "Car Rental & Taxi Services": "Car Rental & Taxi Services",
    "Card Games": "Card Games",
    "Cards & Greetings": "Cards & Greetings",
    "Career Resources & Planning": "Career Resources & Planning",
    "Cargo Trucks & Trailers": "Cargo Trucks & Trailers",
    "Cartoons": "Cartoons",
    "Casual Apparel": "Casual Apparel",
    "Casual Games": "Casual Games",
    "Cats": "Cats",
    "Celebrities & Entertainment News": "Celebrities & Entertainment News",
    "Charity & Philanthropy": "Charity & Philanthropy",
    "Cheerleading": "Cheerleading",
    "Chemicals Industry": "Chemicals Industry",
    "Chemistry": "Chemistry",
    "Chess & Abstract Strategy Games": "Chess & Abstract Strategy Games",
    "Children's Clothing": "Children's Clothing",
    "Children's Interests": "Children's Interests",
    "Children's Literature": "Children's Literature",
    "Circus": "Circus",
    "Classic Vehicles": "Classic Vehicles",
    "Classical Music": "Classical Music",
    "Classifieds": "Classifieds",
    "Cleaning Agents": "Cleaning Agents",
    "Cleaning Services": "Cleaning Services",
    "Climate Change & Global Warming": "Climate Change & Global Warming",
    "Clip Art & Animated GIFs": "Clip Art & Animated GIFs",
    "Clothing Accessories": "Clothing Accessories",
    "Clubs & Organizations": "Clubs & Organizations",
    "Coffee & Tea": "Coffee & Tea",
    "Collectible Card Games": "Collectible Card Games",
    "College Sports": "College Sports",
    "Colleges & Universities": "Colleges & Universities",
    "Combat Sports": "Combat Sports",
    "Comics": "Comics",
    "Comics & Animation": "Comics & Animation",
    "Commercial Properties": "Commercial Properties",
    "Commercial Vehicles": "Commercial Vehicles",
    "Commodities & Futures Trading": "Commodities & Futures Trading",
    "Communications Equipment": "Communications Equipment",
    "Company News": "Company News",
    "Computer & Video Games": "Computer & Video Games",
    "Computer Components": "Computer Components",
    "Computer Drives & Storage": "Computer Drives & Storage",
    "Computer Hardware": "Computer Hardware",
    "Computer Peripherals": "Computer Peripherals",
    "Computer Science": "Computer Science",
    "Computer Security": "Computer Security",
    "Computers & Electronics": "Computers & Electronics",
    "Concerts & Music Festivals": "Concerts & Music Festivals",
    "Construction & Maintenance": "Construction & Maintenance",
    "Construction & Power Tools": "Construction & Power Tools",
    "Consulting": "Consulting",
    "Consumer Advocacy & Protection": "Consumer Advocacy & Protection",
    "Consumer Electronics": "Consumer Electronics",
    "Consumer Resources": "Consumer Resources",
    "Cooking & Recipes": "Cooking & Recipes",
    "Cookware & Diningware": "Cookware & Diningware",
    "Corporate Events": "Corporate Events",
    "Cosmetic Procedures": "Cosmetic Procedures",
    "Cosmetic Surgery": "Cosmetic Surgery",
    "Cosmetology & Beauty Professionals": "Cosmetology & Beauty Professionals",
    "Costumes": "Costumes",
    "Country Music": "Country Music",
    "Coupons & Discount Offers": "Coupons & Discount Offers",
    "Courts & Judiciary": "Courts & Judiciary",
    "Crafts": "Crafts",
    "Credit & Lending": "Credit & Lending",
    "Credit Cards": "Credit Cards",
    "Credit Reporting & Monitoring": "Credit Reporting & Monitoring",
    "Cricket": "Cricket",
    "Crime & Justice": "Crime & Justice",
    "Cruises & Charters": "Cruises & Charters",
    "Currencies & Foreign Exchange": "Currencies & Foreign Exchange",
    "Curtains & Window Treatments": "Curtains & Window Treatments",
    "Cycling": "Cycling",
    "Dance": "Dance",
    "Dance & Electronic Music": "Dance & Electronic Music",
    "Data Formats & Protocols": "Data Formats & Protocols",
    "Data Management": "Data Management",
    "Dating & Personals": "Dating & Personals",
    "Depression": "Depression",
    "Design": "Design",
    "Desktop Computers": "Desktop Computers",
    "Desserts": "Desserts",
    "Device Drivers": "Device Drivers",
    "Diabetes": "Diabetes",
    "Dictionaries & Encyclopedias": "Dictionaries & Encyclopedias",
    "Die-cast & Toy Vehicles": "Die-cast & Toy Vehicles",
    "Directories & Listings": "Directories & Listings",
    "Discrimination & Identity Relations": "Discrimination & Identity Relations",
    "Distance Learning": "Distance Learning",
    "Doctors' Offices": "Doctors' Offices",
    "Dogs": "Dogs",
    "Dolls & Accessories": "Dolls & Accessories",
    "Domestic Services": "Domestic Services",
    "Doors & Windows": "Doors & Windows",
    "Drag & Street Racing": "Drag & Street Racing",
    "Drawing & Coloring": "Drawing & Coloring",
    "Dress-Up & Fashion Games": "Dress-Up & Fashion Games",
    "Driving & Racing Games": "Driving & Racing Games",
    "Drones & RC Aircraft": "Drones & RC Aircraft",
    "Drug & Alcohol Testing": "Drug & Alcohol Testing",
    "Drug & Alcohol Treatment": "Drug & Alcohol Treatment",
    "Drugs & Medications": "Drugs & Medications",
    "E-Books": "E-Books",
    "E-Commerce Services": "E-Commerce Services",
    "Ear Nose & Throat": "Ear Nose & Throat",
    "Earth Sciences": "Earth Sciences",
    "Eating Disorders": "Eating Disorders",
    "Ecology & Environment": "Ecology & Environment",
    "Economics": "Economics",
    "Education": "Education",
    "Electricity": "Electricity",
    "Electronic Components": "Electronic Components",
    "Electronics & Electrical": "Electronics & Electrical",
    "Email & Messaging": "Email & Messaging",
    "Emergency Services": "Emergency Services",
    "Endocrine Conditions": "Endocrine Conditions",
    "Energy & Utilities": "Energy & Utilities",
    "Engineering & Technology": "Engineering & Technology",
    "Enterprise Technology": "Enterprise Technology",
    "Entertainment Industry": "Entertainment Industry",
    "Entertainment Media": "Entertainment Media",
    "Entertainment Media Rentals": "Entertainment Media Rentals",
    "Event Planning": "Event Planning",
    "Events & Listings": "Events & Listings",
    "Exotic Pets": "Exotic Pets",
    "Experimental & Industrial Music": "Experimental & Industrial Music",
    "Expos & Conventions": "Expos & Conventions",
    "Extreme Sports": "Extreme Sports",
    "Eyeglasses & Contacts": "Eyeglasses & Contacts",
    "Eyewear": "Eyewear",
    "Face & Body Care": "Face & Body Care",
    "Family": "Family",
    "Family & Relationships": "Family & Relationships",
    "Family-Oriented Games & Activities": "Family-Oriented Games & Activities",
    "Fan Fiction": "Fan Fiction",
    "Fantasy Sports": "Fantasy Sports",
    "Fashion & Style": "Fashion & Style",
    "Fashion Designers & Collections": "Fashion Designers & Collections",
    "Fast Food": "Fast Food",
    "Fiber & Textile Arts": "Fiber & Textile Arts",
    "Fighting Games": "Fighting Games",
    "File Sharing & Hosting": "File Sharing & Hosting",
    "Film & TV Industry": "Film & TV Industry",
    "Film Festivals": "Film Festivals",
    "Finance": "Finance",
    "Financial Markets News": "Financial Markets News",
    "Financial Planning & Management": "Financial Planning & Management",
    "Fire & Security Services": "Fire & Security Services",
    "Fireplaces & Stoves": "Fireplaces & Stoves",
    "Fish & Aquaria": "Fish & Aquaria",
    "Fishing": "Fishing",
    "Fitness": "Fitness",
    "Flash-Based Entertainment": "Flash-Based Entertainment",
    "Flooring": "Flooring",
    "Flowers": "Flowers",
    "Food": "Food",
    "Food & Drink": "Food & Drink",
    "Food & Grocery Retailers": "Food & Grocery Retailers",
    "Food Service": "Food Service",
    "Footwear": "Footwear",
    "Foreign Language Resources": "Foreign Language Resources",
    "Forestry": "Forestry",
    "Formal Wear": "Formal Wear",
    "Forms Guides & Templates": "Forms Guides & Templates",
    "Freight & Trucking": "Freight & Trucking",
    "Fun & Trivia": "Fun & Trivia",
    "Fun Tests & Silly Surveys": "Fun Tests & Silly Surveys",
    "Funny Pictures & Videos": "Funny Pictures & Videos",
    "GPS & Navigation": "GPS & Navigation",
    "Gambling": "Gambling",
    "Game Systems & Consoles": "Game Systems & Consoles",
    "Games": "Games",
    "Gardening & Landscaping": "Gardening & Landscaping",
    "Gas Prices & Vehicle Fueling": "Gas Prices & Vehicle Fueling",
    "General Reference": "General Reference",
    "Genetic Disorders": "Genetic Disorders",
    "Geographic Reference": "Geographic Reference",
    "Geology": "Geology",
    "Gifts": "Gifts",
    "Gifts & Special Event Items": "Gifts & Special Event Items",
    "Golf": "Golf",
    "Gossip & Tabloid News": "Gossip & Tabloid News",
    "Government": "Government",
    "Grains & Pasta": "Grains & Pasta",
    "Grants, Scholarships & Financial Aid": "Grants, Scholarships & Financial Aid",
    "Green Living & Environmental Issues": "Green Living & Environmental Issues",
    "Gymnastics": "Gymnastics",
    "HVAC & Climate Control": "HVAC & Climate Control",
    "Hacking & Cracking": "Hacking & Cracking",
    "Hair Care": "Hair Care",
    "Hair Loss": "Hair Loss",
    "Headwear": "Headwear",
    "Health": "Health",
    "Health Conditions": "Health Conditions",
    "Health Education & Medical Training": "Health Education & Medical Training",
    "Health Foundations & Medical Research": "Health Foundations & Medical Research",
    "Health Insurance": "Health Insurance",
    "Health News": "Health News",
    "Heart & Hypertension": "Heart & Hypertension",
    "Heavy Machinery": "Heavy Machinery",
    "Hiking & Camping": "Hiking & Camping",
    "History": "History",
    "Hobbies & Leisure": "Hobbies & Leisure",
    "Hockey": "Hockey",
    "Holidays & Seasonal Events": "Holidays & Seasonal Events",
    "Home & Garden": "Home & Garden",
    "Home & Interior Decor": "Home & Interior Decor",
    "Home Appliances": "Home Appliances",
    "Home Furnishings": "Home Furnishings",
    "Home Improvement": "Home Improvement",
    "Home Safety & Security": "Home Safety & Security",
    "Home Storage & Shelving": "Home Storage & Shelving",
    "Home Swimming Pools, Saunas & Spas": "Home Swimming Pools, Saunas & Spas",
    "Homeschooling": "Homeschooling",
    "Horses": "Horses",
    "Hospitality Industry": "Hospitality Industry",
    "Hospitals & Treatment Centers": "Hospitals & Treatment Centers",
    "Hotels & Accommodations": "Hotels & Accommodations",
    "House Painting & Finishing": "House Painting & Finishing",
    "Human Rights & Liberties": "Human Rights & Liberties",
    "Humanities": "Humanities",
    "Humor": "Humor",
    "Hybrid & Alternative Vehicles": "Hybrid & Alternative Vehicles",
    "Hygiene & Toiletries": "Hygiene & Toiletries",
    "Ice Skating": "Ice Skating",
    "Individual Sports": "Individual Sports",
    "Industrial Materials & Equipment": "Industrial Materials & Equipment",
    "Infectious Diseases": "Infectious Diseases",
    "Insurance": "Insurance",
    "International Sports Competitions": "International Sports Competitions",
    "Internet & Telecom": "Internet & Telecom",
    "Internet Software": "Internet Software",
    "Investing": "Investing",
    "Java (Programming Language)": "Java (Programming Language)",
    "Jazz & Blues": "Jazz & Blues",
    "Job Listings": "Job Listings",
    "Jobs": "Jobs",
    "Jobs & Education": "Jobs & Education",
    "Juice": "Juice",
    "Kids & Teens": "Kids & Teens",
    "Kitchen & Dining": "Kitchen & Dining",
    "Kitchen & Dining Furniture": "Kitchen & Dining Furniture",
    "Lamps & Lighting": "Lamps & Lighting",
    "Language Resources": "Language Resources",
    "Laptops & Notebooks": "Laptops & Notebooks",
    "Laundry": "Laundry",
    "Law & Government": "Law & Government",
    "Law Enforcement": "Law Enforcement",
    "Lawn Mowers": "Lawn Mowers",
    "Legal": "Legal",
    "Legal Education": "Legal Education",
    "Legal Services": "Legal Services",
    "Libraries & Museums": "Libraries & Museums",
    "Literary Classics": "Literary Classics",
    "Livestock": "Livestock",
    "Living Room Furniture": "Living Room Furniture",
    "Loans": "Loans",
    "Lots & Land": "Lots & Land",
    "Lottery": "Lottery",
    "Luxury Goods": "Luxury Goods",
    "MLM & Business Opportunities": "MLM & Business Opportunities",
    "Magic": "Magic",
    "Mail & Package Delivery": "Mail & Package Delivery",
    "Major Kitchen Appliances": "Major Kitchen Appliances",
    "Make-Up & Cosmetics": "Make-Up & Cosmetics",
    "Management": "Management",
    "Manufacturing": "Manufacturing",
    "Maps": "Maps",
    "Maritime Transport": "Maritime Transport",
    "Marriage": "Marriage",
    "Martial Arts": "Martial Arts",
    "Mass Merchants & Department Stores": "Mass Merchants & Department Stores",
    "Massage Therapy": "Massage Therapy",
    "Massively Multiplayer Games": "Massively Multiplayer Games",
    "Mathematics": "Mathematics",
    "Matrimonial Services": "Matrimonial Services",
    "Meat & Seafood": "Meat & Seafood",
    "Medical Devices & Equipment": "Medical Devices & Equipment",
    "Medical Facilities & Services": "Medical Facilities & Services",
    "Medical Procedures": "Medical Procedures",
    "Men's Clothing": "Men's Clothing",
    "Men's Health": "Men's Health",
    "Mental Health": "Mental Health",
    "Merit Prizes & Contests": "Merit Prizes & Contests",
    "Metals & Mining": "Metals & Mining",
    "Military": "Military",
    "Miniatures & Wargaming": "Miniatures & Wargaming",
    "Mobile & Wireless": "Mobile & Wireless",
    "Mobile & Wireless Accessories": "Mobile & Wireless Accessories",
    "Mobile Apps & Add-Ons": "Mobile Apps & Add-Ons",
    "Mobile Phones": "Mobile Phones",
    "Model Trains & Railroads": "Model Trains & Railroads",
    "Motor Sports": "Motor Sports",
    "Motor Vehicles (By Type)": "Motor Vehicles (By Type)",
    "Motorcycles": "Motorcycles",
    "Mountain & Ski Resorts": "Mountain & Ski Resorts",
    "Movie Listings & Theater Showtimes": "Movie Listings & Theater Showtimes",
    "Movies": "Movies",
    "Moving & Relocation": "Moving & Relocation",
    "Multimedia Software": "Multimedia Software",
    "Museums": "Museums",
    "Music & Audio": "Music & Audio",
    "Music & Dance Games": "Music & Dance Games",
    "Music Education & Instruction": "Music Education & Instruction",
    "Music Equipment & Technology": "Music Equipment & Technology",
    "Music Reference": "Music Reference",
    "Music Streams & Downloads": "Music Streams & Downloads",
    "Music Videos": "Music Videos",
    "Myth & Folklore": "Myth & Folklore",
    "Network Monitoring & Management": "Network Monitoring & Management",
    "Networking": "Networking",
    "Neurological Conditions": "Neurological Conditions",
    "Neuroscience": "Neuroscience",
    "News": "News",
    "Nursery & Playroom": "Nursery & Playroom",
    "Nursing": "Nursing",
    "Nutrition": "Nutrition",
    "Obesity": "Obesity",
    "Occult & Paranormal": "Occult & Paranormal",
    "Occupational Health & Safety": "Occupational Health & Safety",
    "Off-Road Vehicles": "Off-Road Vehicles",
    "Offbeat": "Offbeat",
    "Office Services": "Office Services",
    "Office Supplies": "Office Supplies",
    "Oil & Gas": "Oil & Gas",
    "Olympics": "Olympics",
    "Online Communities": "Online Communities",
    "Online Games": "Online Games",
    "Online Goodies": "Online Goodies",
    "Online Image Galleries": "Online Image Galleries",
    "Online Media": "Online Media",
    "Online Video": "Online Video",
    "Opera": "Opera",
    "Operating Systems": "Operating Systems",
    "Oral & Dental Care": "Oral & Dental Care",
    "Outdoors": "Outdoors",
    "Packaging": "Packaging",
    "Pain Management": "Pain Management",
    "Paintball": "Paintball",
    "Painting": "Painting",
    "Parking": "Parking",
    "People & Society": "People & Society",
    "Performing Arts": "Performing Arts",
    "Perfumes & Fragrances": "Perfumes & Fragrances",
    "Personals": "Personals",
    "Pest Control": "Pest Control",
    "Pet Food & Supplies": "Pet Food & Supplies",
    "Pets": "Pets",
    "Pets & Animals": "Pets & Animals",
    "Pharmaceuticals & Biotech": "Pharmaceuticals & Biotech",
    "Pharmacy": "Pharmacy",
    "Philosophy": "Philosophy",
    "Photo & Image Sharing": "Photo & Image Sharing",
    "Photo & Video Services": "Photo & Video Services",
    "Photo & Video Sharing": "Photo & Video Sharing",
    "Photo Rating Sites": "Photo Rating Sites",
    "Photographic & Digital Arts": "Photographic & Digital Arts",
    "Physical Therapy": "Physical Therapy",
    "Physics": "Physics",
    "Pizzerias": "Pizzerias",
    "Plastics & Polymers": "Plastics & Polymers",
    "Plumbing": "Plumbing",
    "Poetry": "Poetry",
    "Poker & Casino Games": "Poker & Casino Games",
    "Political Humor": "Political Humor",
    "Political Science": "Political Science",
    "Politics": "Politics",
    "Pop Music": "Pop Music",
    "Poverty & Hunger": "Poverty & Hunger",
    "Power Supplies": "Power Supplies",
    "Precious Metals": "Precious Metals",
    "Primary & Secondary Schooling (K-12)": "Primary & Secondary Schooling (K-12)",
    "Printing & Publishing": "Printing & Publishing",
    "Product Reviews & Price Comparisons": "Product Reviews & Price Comparisons",
    "Programming": "Programming",
    "Psychology": "Psychology",
    "Public Health": "Public Health",
    "Public Records": "Public Records",
    "Public Relations": "Public Relations",
    "Public Safety": "Public Safety",
    "Puzzles & Brainteasers": "Puzzles & Brainteasers",
    "Rabbits & Rodents": "Rabbits & Rodents",
    "Racquet Sports": "Racquet Sports",
    "Radio": "Radio",
    "Radio Control & Modeling": "Radio Control & Modeling",
    "Radio Equipment": "Radio Equipment",
    "Rail Transport": "Rail Transport",
    "Real Estate": "Real Estate",
    "Real Estate Listings": "Real Estate Listings",
    "Real Estate Services": "Real Estate Services",
    "Recording Industry": "Recording Industry",
    "Reference": "Reference",
    "Regional Parks & Gardens": "Regional Parks & Gardens",
    "Religion & Belief": "Religion & Belief",
    "Religious Music": "Religious Music",
    "Renewable & Alternative Energy": "Renewable & Alternative Energy",
    "Reproductive Health": "Reproductive Health",
    "Reptiles & Amphibians": "Reptiles & Amphibians",
    "Residential Rentals": "Residential Rentals",
    "Residential Sales": "Residential Sales",
    "Respiratory Conditions": "Respiratory Conditions",
    "Restaurant Reviews & Reservations": "Restaurant Reviews & Reservations",
    "Restaurants": "Restaurants",
    "Resumes & Portfolios": "Resumes & Portfolios",
    "Retail Equipment & Technology": "Retail Equipment & Technology",
    "Retail Trade": "Retail Trade",
    "Retirement & Pension": "Retirement & Pension",
    "Ride-On Toys & Wagons": "Ride-On Toys & Wagons",
    "Robotics": "Robotics",
    "Rock Music": "Rock Music",
    "Roleplaying Games": "Roleplaying Games",
    "Rugby": "Rugby",
    "Rugs & Carpets": "Rugs & Carpets",
    "Sandbox Games": "Sandbox Games",
    "Scandals & Investigations": "Scandals & Investigations",
    "Science": "Science",
    "Scientific Institutions": "Scientific Institutions",
    "Security Products & Services": "Security Products & Services",
    "Seniors & Retirement": "Seniors & Retirement",
    "Sensitive Subjects": "Sensitive Subjects",
    "Service Providers": "Service Providers",
    "Shooter Games": "Shooter Games",
    "Shopping": "Shopping",
    "Simulation Games": "Simulation Games",
    "Skate Sports": "Skate Sports",
    "Skiing & Snowboarding": "Skiing & Snowboarding",
    "Skin & Nail Care": "Skin & Nail Care",
    "Skin Conditions": "Skin Conditions",
    "Skins, Themes & Wallpapers": "Skins, Themes & Wallpapers",
    "Sleep Disorders": "Sleep Disorders",
    "Small Business": "Small Business",
    "Small Kitchen Appliances": "Small Kitchen Appliances",
    "Smoking & Smoking Cessation": "Smoking & Smoking Cessation",
    "Snack Foods": "Snack Foods",
    "Soccer": "Soccer",
    "Social Issues & Advocacy": "Social Issues & Advocacy",
    "Social Network Apps & Add-Ons": "Social Network Apps & Add-Ons",
    "Social Networks": "Social Networks",
    "Social Sciences": "Social Sciences",
    "Social Services": "Social Services",
    "Soft Drinks": "Soft Drinks",
    "Software": "Software",
    "Software Utilities": "Software Utilities",
    "Soundtracks": "Soundtracks",
    "Soups & Stews": "Soups & Stews",
    "Space Technology": "Space Technology",
    "Spas & Beauty Services": "Spas & Beauty Services",
    "Special & Restricted Diets": "Special & Restricted Diets",
    "Special Occasions": "Special Occasions",
    "Specialty Travel": "Specialty Travel",
    "Sporting Goods": "Sporting Goods",
    "Sports": "Sports",
    "Sports Coaching & Training": "Sports Coaching & Training",
    "Sports Games": "Sports Games",
    "Sports Memorabilia": "Sports Memorabilia",
    "Sports News": "Sports News",
    "Standardized & Admissions Tests": "Standardized & Admissions Tests",
    "Statistics": "Statistics",
    "Steroids & Performance-Enhancing Drugs": "Steroids & Performance-Enhancing Drugs",
    "Stocks & Bonds": "Stocks & Bonds",
    "Strategy Games": "Strategy Games",
    "Study Grants & Scholarships": "Study Grants & Scholarships",
    "Stuffed Toys": "Stuffed Toys",
    "Subcultures & Niche Interests": "Subcultures & Niche Interests",
    "Substance Abuse": "Substance Abuse",
    "Surf & Swim": "Surf & Swim",
    "Surfing": "Surfing",
    "Swimming": "Swimming",
    "Swimwear": "Swimwear",
    "TV & Video": "TV & Video",
    "TV & Video Equipment": "TV & Video Equipment",
    "TV Commercials": "TV Commercials",
    "TV Shows & Programs": "TV Shows & Programs",
    "Table Games": "Table Games",
    "Tax Preparation & Planning": "Tax Preparation & Planning",
    "Teaching & Classroom Resources": "Teaching & Classroom Resources",
    "Team Sports": "Team Sports",
    "Teen Interests": "Teen Interests",
    "Text & Instant Messaging": "Text & Instant Messaging",
    "Textiles & Nonwovens": "Textiles & Nonwovens",
    "Theme Parks": "Theme Parks",
    "Time & Calendars": "Time & Calendars",
    "Timeshares & Vacation Properties": "Timeshares & Vacation Properties",
    "Tobacco Products": "Tobacco Products",
    "Tourist Destinations": "Tourist Destinations",
    "Toys": "Toys",
    "Track & Field": "Track & Field",
    "Training & Certification": "Training & Certification",
    "Transportation & Logistics": "Transportation & Logistics",
    "Travel": "Travel",
    "Troubled Relationships": "Troubled Relationships",
    "Trucks & SUVs": "Trucks & SUVs",
    "Undergarments": "Undergarments",
    "Unwanted Body & Facial Hair Removal": "Unwanted Body & Facial Hair Removal",
    "Urban & Hip-Hop": "Urban & Hip-Hop",
    "Urban Transport": "Urban Transport",
    "Used Vehicles": "Used Vehicles",
    "VPN & Remote Access": "VPN & Remote Access",
    "Vacation Rentals & Short-Term Stays": "Vacation Rentals & Short-Term Stays",
    "Vehicle Codes & Driving Laws": "Vehicle Codes & Driving Laws",
    "Vehicle Licensing & Registration": "Vehicle Licensing & Registration",
    "Vehicle Parts & Accessories": "Vehicle Parts & Accessories",
    "Vehicle Parts & Services": "Vehicle Parts & Services",
    "Vehicle Repair & Maintenance": "Vehicle Repair & Maintenance",
    "Vehicle Shopping": "Vehicle Shopping",
    "Vehicle Shows": "Vehicle Shows",
    "Venture Capital": "Venture Capital",
    "Veterinarians": "Veterinarians",
    "Video Game Emulation": "Video Game Emulation",
    "Virtual Worlds": "Virtual Worlds",
    "Visa & Immigration": "Visa & Immigration",
    "Vision Care": "Vision Care",
    "Visual Art & Design": "Visual Art & Design",
    "Vitamins & Supplements": "Vitamins & Supplements",
    "Vocational & Continuing Education": "Vocational & Continuing Education",
    "Voice & Video Chat": "Voice & Video Chat",
    "Volleyball": "Volleyball",
    "Washers & Dryers": "Washers & Dryers",
    "Water Activities": "Water Activities",
    "Water Sports": "Water Sports",
    "Weather": "Weather",
    "Web Design & Development": "Web Design & Development",
    "Web Services": "Web Services",
    "Weddings": "Weddings",
    "Weight Loss": "Weight Loss",
    "Wildlife": "Wildlife",
    "Winter Sports": "Winter Sports",
    "Winter Sports Equipment": "Winter Sports Equipment",
    "Women's Clothing": "Women's Clothing",
    "Women's Health": "Women's Health",
    "Word Games": "Word Games",
    "Work & Labor Issues": "Work & Labor Issues",
    "World Music": "World Music",
    "Wrestling": "Wrestling",
    "Writers Resources": "Writers Resources",
    "Writing & Editing Services": "Writing & Editing Services",
    "Yard & Patio": "Yard & Patio",
    "Youth Organizations & Resources": "Youth Organizations & Resources",
    "Zoos-Aquariums-Preserves": "Zoos-Aquariums-Preserves"
}

export const DataFilterSortOptions = {
    "Ads I don’t want to see": "Ads I don’t want to see"
}

export const SiteColors = {
    "purple": "#4153F1",
    "orange": "#FF7534",
    "green": "#1FE6B6",
    "red": "#E61F1F"
}

export const PublicRoutes = [
    '/auth',
    '/discover',
    '/pages/[siteUrl]',
    '/pages/[[...publicUrl]]',
    '/terms-and-conditions',
    '/privacy-policy',
]

export const greyImage = 'https://storage.googleapis.com/trivsel-a74a1.appspot.com/dummy_photos/dummy_content_image.png';
